image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0

stages:
  - mvn-package
  - mvn-sonar

maven-branches:
  stage: mvn-package
  script:
    - mvn clean && mvn install -U -DskipTests=false
  only:
    - branches

maven-sonar:
  stage: mvn-sonar
  script:
    - mvn clean && mvn install -U -DskipTests=false
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.analysis.serviceGroup=$GROUP_NAME -Dsonar.analysis.commitId=$CI_COMMIT_SHA -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
  except:
    - tags

.auto_devops: &auto_devops |
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=lib"
    source .auto_devops.sh

before_script:
  - *auto_devops